DROP TABLE IF EXISTS vehicles;
CREATE TABLE IF NOT EXISTS vehicles (
  id SERIAL PRIMARY KEY,
  image_Url VARCHAR(100),
  "name" VARCHAR (500) NOT NULL,
  model VARCHAR (100) NOT NULL,
  "length" VARCHAR(5000) NOT NULL,
  cargo_capacity VARCHAR (8000)
);

CREATE TABLE IF NOT EXISTS recentSearches(
id SERIAL PRIMARY KEY,
search VARCHAR(500) NOT NULL
);