CREATE TABLE IF NOT EXISTS vehicles (
  id SERIAL PRIMARY KEY,
  Imag_Url VARCHAR(100),
  "name" VARCHAR (500) NOT NULL,
  model VARCHAR (100) NOT NULL,
  "length" VARCHAR(5000) NOT NULL,
  cargo_capacity VARCHAR (8000) NOT NULL
);
